name: Run Selenium Tests

on:
  push:
    branches:
      - enhancement-for-fyp

jobs:
  selenium-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requirements.txt
    - name: Run Selenium tests
      run: |
        python manage.py test tests.SeleniumTestCase
